services:
  api:
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  teslamate:
    image: teslamate/teslamate:latest
    restart: always
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
    ports:
      - 4000:4000
    volumes:
      - ./import:/opt/app/import
    cap_drop:
      - all

  database:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=teslamate
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_DB=teslamate
    volumes:
      - teslamate-db:/var/lib/postgresql/data

  # grafana:
  #   image: teslamate/grafana:latest
  #   restart: always
  #   environment:
  #     - DATABASE_USER=teslamate
  #     - DATABASE_PASS=${DATABASE_PASS}
  #     - DATABASE_NAME=teslamate
  #     - DATABASE_HOST=database
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - teslamate-grafana-data:/var/lib/grafana

  mosquitto:
    image: eclipse-mosquitto:2
    restart: always
    command: mosquitto -c /mosquitto-no-auth.conf
    ports:
      - 1883:1883
    volumes:
      - mosquitto-conf:/mosquitto/config
      - mosquitto-data:/mosquitto/data

  teslamateapi:
    image: tobiasehlert/teslamateapi:latest
    restart: always
    depends_on:
      - database
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - DATABASE_USER=teslamate
      - DATABASE_PASS=${DATABASE_PASS}
      - DATABASE_NAME=teslamate
      - DATABASE_HOST=database
      - MQTT_HOST=mosquitto
      - TZ=America/New_York
    ports:
      - 8080:8080

  mediawiki:
    build:
      context: ./mediawiki
      dockerfile: Dockerfile
    volumes:
      - wikidata:/var/www/html
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
  
  nginx:
    depends_on:
      - api
      - mediawiki
    image: nginx:1.21.5-alpine
    volumes:
      - ./nginx/mediawiki.conf:/etc/nginx/nginx.conf
      - wikidata:/var/www/html
    ports:
      - 80:80
  
  mediawikidb:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: wikiuser
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: wikidb
    volumes:
      - dbdata:/var/lib/postgresql/data

  ngrok:
    depends_on:
      - nginx
    image: ngrok/ngrok
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    command: http nginx:80 --url="${NGROK_SUBDOMAIN}.ngrok.io"
    ports:
      - "4040:4040"

volumes:
  teslamate-db:
  teslamate-grafana-data:
  mosquitto-conf:
  mosquitto-data:
  wikidata:
  dbdata: